=== IBM/report-toolkit/packages/common/diagnostic-report-v2.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "DiagnosticReport": {
      "properties": {
        "environmentVariables": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "header": {
          "$ref": "#/definitions/ReportHeader"
        },
        "javascriptHeap": {
          "$ref": "#/definitions/ReportJSHeap"
        },
        "javascriptStack": {
          "$ref": "#/definitions/ReportJSStack"
        },
        "libuv": {
          "items": {
            "properties": {},
            "type": "object"
          },
          "type": "array"
        },
        "nativeStack": {
          "items": {
            "$ref": "#/definitions/NativeStackFrame"
          },
          "type": "array"
        },
        "resourceUsage": {
          "$ref": "#/definitions/ReportResourceUsage"
        },
        "sharedObjects": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "userLimits": {
          "additionalProperties": {
            "$ref": "#/definitions/ReportUserLimit"
          },
          "type": "object"
        },
        "workers": {
          "items": {
            "$ref": "#/definitions/DiagnosticReport"
          },
          "type": "array"
        }
      },
      "required": [
        "environmentVariables",
        "header",
        "javascriptHeap",
        "javascriptStack",
        "libuv",
        "nativeStack",
        "resourceUsage",
        "sharedObjects",
        "workers"
      ],
      "type": "object"
    },
    "NativeStackFrame": {
      "properties": {
        "pc": {
          "type": "string"
        },
        "symbol": {
          "type": "string"
        }
      },
      "required": ["pc", "symbol"],
      "type": "object"
    },
    "ReportHeader": {
      "properties": {
        "arch": {
          "type": "string"
        },
        "commandLine": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "componentVersions": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "cpus": {
          "items": {
            "$ref": "#/definitions/ReportHeaderCpu"
          },
          "type": "array"
        },
        "cwd": {
          "type": "string"
        },
        "dumpEventTime": {
          "type": "string"
        },
        "dumpEventTimeStamp": {
          "type": "string"
        },
        "event": {
          "type": "string"
        },
        "filename": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "nodejsVersion": {
          "type": "string"
        },
        "osMachine": {
          "type": "string"
        },
        "osName": {
          "type": "string"
        },
        "osRelease": {
          "type": "string"
        },
        "osVersion": {
          "type": "string"
        },
        "platform": {
          "type": "string"
        },
        "processId": {
          "type": "number"
        },
        "release": {
          "properties": {
            "headersUrl": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "sourceUrl": {
              "type": "string"
            }
          },
          "required": ["headersUrl", "name", "sourceUrl"],
          "type": "object"
        },
        "threadId": {
          "type": ["null", "number"]
        },
        "trigger": {
          "type": "string"
        },
        "wordSize": {
          "type": "number"
        }
      },
      "required": [
        "arch",
        "commandLine",
        "componentVersions",
        "cpus",
        "cwd",
        "dumpEventTime",
        "dumpEventTimeStamp",
        "event",
        "filename",
        "host",
        "nodejsVersion",
        "osMachine",
        "osName",
        "osRelease",
        "osVersion",
        "platform",
        "processId",
        "release",
        "threadId",
        "trigger",
        "wordSize"
      ],
      "type": "object"
    },
    "ReportHeaderCpu": {
      "properties": {
        "idle": {
          "type": "number"
        },
        "irq": {
          "type": "number"
        },
        "model": {
          "type": "string"
        },
        "nice": {
          "type": "number"
        },
        "speed": {
          "type": "number"
        },
        "sys": {
          "type": "number"
        },
        "user": {
          "type": "number"
        }
      },
      "required": ["idle", "irq", "model", "nice", "speed", "sys", "user"],
      "type": "object"
    },
    "ReportHeapSpace": {
      "properties": {
        "available": {
          "type": "number"
        },
        "capacity": {
          "type": "number"
        },
        "committedMemory": {
          "type": "number"
        },
        "memorySize": {
          "type": "number"
        },
        "used": {
          "type": "number"
        }
      },
      "required": [
        "available",
        "capacity",
        "committedMemory",
        "memorySize",
        "used"
      ],
      "type": "object"
    },
    "ReportJSHeap": {
      "properties": {
        "availableMemory": {
          "type": "number"
        },
        "heapSpaces": {
          "additionalProperties": {
            "$ref": "#/definitions/ReportHeapSpace"
          },
          "type": "object"
        },
        "memoryLimit": {
          "type": "number"
        },
        "totalCommittedMemory": {
          "type": "number"
        },
        "totalMemory": {
          "type": "number"
        },
        "usedMemory": {
          "type": "number"
        }
      },
      "required": [
        "availableMemory",
        "heapSpaces",
        "memoryLimit",
        "totalCommittedMemory",
        "totalMemory",
        "usedMemory"
      ],
      "type": "object"
    },
    "ReportJSStack": {
      "properties": {
        "message": {
          "type": "string"
        },
        "stack": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": ["message", "stack"],
      "type": "object"
    },
    "ReportResourceUsage": {
      "properties": {
        "cpuConsumptionPercent": {
          "type": "number"
        },
        "fsActivity": {
          "properties": {
            "reads": {
              "type": "number"
            },
            "writes": {
              "type": "number"
            }
          },
          "required": ["reads", "writes"],
          "type": "object"
        },
        "kernelCpuSeconds": {
          "type": "number"
        },
        "maxRss": {
          "type": "number"
        },
        "pageFaults": {
          "properties": {
            "IONotRequired": {
              "type": "number"
            },
            "IORequired": {
              "type": "number"
            }
          },
          "required": ["IONotRequired", "IORequired"],
          "type": "object"
        },
        "userCpuSeconds": {
          "type": "number"
        }
      },
      "required": [
        "cpuConsumptionPercent",
        "fsActivity",
        "kernelCpuSeconds",
        "maxRss",
        "pageFaults",
        "userCpuSeconds"
      ],
      "type": "object"
    },
    "ReportUserLimit": {
      "properties": {
        "hard": {
          "anyOf": [
            {
              "enum": ["unlimited"],
              "type": "string"
            },
            {
              "type": "number"
            }
          ]
        },
        "soft": {
          "anyOf": [
            {
              "enum": ["unlimited"],
              "type": "string"
            },
            {
              "type": "number"
            }
          ]
        }
      },
      "required": ["hard", "soft"],
      "type": "object"
    }
  },
  "properties": {
    "environmentVariables": {
      "additionalProperties": {
        "type": "string"
      },
      "type": "object"
    },
    "header": {
      "$ref": "#/definitions/ReportHeader"
    },
    "javascriptHeap": {
      "$ref": "#/definitions/ReportJSHeap"
    },
    "javascriptStack": {
      "$ref": "#/definitions/ReportJSStack"
    },
    "libuv": {
      "items": {
        "properties": {},
        "type": "object"
      },
      "type": "array"
    },
    "nativeStack": {
      "items": {
        "$ref": "#/definitions/NativeStackFrame"
      },
      "type": "array"
    },
    "resourceUsage": {
      "$ref": "#/definitions/ReportResourceUsage"
    },
    "sharedObjects": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "userLimits": {
      "additionalProperties": {
        "$ref": "#/definitions/ReportUserLimit"
      },
      "type": "object"
    },
    "workers": {
      "items": {
        "$ref": "#/definitions/DiagnosticReport"
      },
      "type": "array"
    }
  },
  "required": [
    "environmentVariables",
    "header",
    "javascriptHeap",
    "javascriptStack",
    "libuv",
    "nativeStack",
    "resourceUsage",
    "sharedObjects",
    "workers"
  ],
  "type": "object"
}

=== IBM/report-toolkit/packages/common/test/fixture/reports/report-001.json
{
  "header": {
    "reportVersion": 2,
    "event": "JavaScript API",
    "trigger": "API",
    "filename": "report.20190429.123135.45164.0.001.json",
    "dumpEventTime": "2019-04-29T12:31:35Z",
    "dumpEventTimeStamp": "1556566295950",
    "processId": 45164,
    "threadId": 0,
    "cwd": "/Users/boneskull/projects/christopher-hiller/report-toolkit",
    "commandLine": [
      "node",
      "--experimental-report",
      "-e",
      "process.report.writeReport()"
    ],
    "nodejsVersion": "v12.1.0",
    "wordSize": 64,
    "arch": "x64",
    "platform": "darwin",
    "componentVersions": {
      "node": "12.1.0",
      "v8": "7.4.288.21-node.16",
      "uv": "1.28.0",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.38.0",
      "napi": "4",
      "llhttp": "1.1.1",
      "http_parser": "2.8.0",
      "openssl": "1.1.1b",
      "cldr": "35.1",
      "icu": "64.2",
      "tz": "2019a",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "headersUrl": "https://nodejs.org/download/release/v12.1.0/node-v12.1.0-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v12.1.0/node-v12.1.0.tar.gz"
    },
    "osName": "Darwin",
    "osRelease": "18.5.0",
    "osVersion": "Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64",
    "osMachine": "x86_64",
    "cpus": [
      {
        "model": "Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz",
        "speed": 2700,
        "user": 123707280,
        "nice": 0,
        "sys": 80585050,
        "idle": 303826800,
        "irq": 0
      }
    ],
    "host": "yoyodyne"
  },
  "javascriptStack": {
    "message": "Error [ERR_SYNTHETIC]: JavaScript Callstack",
    "stack": [
      "at Object.writeReport (internal/process/report.js:16:13)",
      "at [eval]:1:16",
      "at Script.runInThisContext (vm.js:123:20)",
      "at Object.runInThisContext (vm.js:313:38)",
      "at Object.<anonymous> ([eval]-wrapper:9:26)",
      "at Module._compile (internal/modules/cjs/loader.js:759:30)",
      "at evalScript (internal/process/execution.js:79:25)"
    ]
  },
  "nativeStack": [
    {
      "pc": "0x000000010013cc86",
      "symbol": "report::TriggerNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, v8::Local<v8::String>) [/Users/boneskull/.nvm/versions/node/v12.1.0/bin/node]"
    },
    {
      "pc": "0x0000000100143fa7",
      "symbol": "report::WriteReport(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/boneskull/.nvm/versions/node/v12.1.0/bin/node]"
    },
    {
      "pc": "0x00000001001e6494",
      "symbol": "v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/boneskull/.nvm/versions/node/v12.1.0/bin/node]"
    },
    {
      "pc": "0x00000001001e5aa4",
      "symbol": "v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/boneskull/.nvm/versions/node/v12.1.0/bin/node]"
    },
    {
      "pc": "0x00000001001e5050",
      "symbol": "v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/boneskull/.nvm/versions/node/v12.1.0/bin/node]"
    },
    {
      "pc": "0x0000000100e9b482",
      "symbol": "Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/boneskull/.nvm/versions/node/v12.1.0/bin/node]"
    },
    {
      "pc": "0x0000000100e05904",
      "symbol": "Builtins_InterpreterEntryTrampoline [/Users/boneskull/.nvm/versions/node/v12.1.0/bin/node]"
    }
  ],
  "javascriptHeap": {
    "totalMemory": 5009408,
    "totalCommittedMemory": 3317120,
    "usedMemory": 2277880,
    "availableMemory": 2194567328,
    "memoryLimit": 2197815296,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 524288,
        "committedMemory": 32024,
        "capacity": 523976,
        "used": 31712,
        "available": 492264
      },
      "new_space": {
        "memorySize": 2097152,
        "committedMemory": 1847840,
        "capacity": 1047952,
        "used": 826856,
        "available": 221096
      },
      "old_space": {
        "memorySize": 1171456,
        "committedMemory": 1021208,
        "capacity": 1020400,
        "used": 1020272,
        "available": 128
      },
      "code_space": {
        "memorySize": 688128,
        "committedMemory": 165984,
        "capacity": 149600,
        "used": 149600,
        "available": 0
      },
      "map_space": {
        "memorySize": 528384,
        "committedMemory": 250064,
        "capacity": 249440,
        "used": 249440,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 0,
        "used": 0,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 0,
        "used": 0,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 1047952,
        "used": 0,
        "available": 1047952
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 0.047874,
    "kernelCpuSeconds": 0.013338,
    "cpuConsumptionPercent": 6.1212,
    "maxRss": 23035117568,
    "pageFaults": {
      "IORequired": 0,
      "IONotRequired": 5823
    },
    "fsActivity": {
      "reads": 0,
      "writes": 0
    }
  },
  "libuv": [
    {
      "type": "async",
      "is_active": true,
      "is_referenced": false,
      "address": "0x000000010301d9e0"
    },
    {
      "type": "timer",
      "is_active": false,
      "is_referenced": false,
      "address": "0x0000000105041750",
      "repeat": 0,
      "firesInMsFromNow": -354721149,
      "expired": true
    },
    {
      "type": "check",
      "is_active": true,
      "is_referenced": false,
      "address": "0x00000001050417e8"
    },
    {
      "type": "idle",
      "is_active": false,
      "is_referenced": true,
      "address": "0x0000000105041860"
    },
    {
      "type": "prepare",
      "is_active": false,
      "is_referenced": false,
      "address": "0x00000001050418d8"
    },
    {
      "type": "check",
      "is_active": false,
      "is_referenced": false,
      "address": "0x0000000105041950"
    },
    {
      "type": "async",
      "is_active": true,
      "is_referenced": false,
      "address": "0x000000010321cf80"
    },
    {
      "type": "async",
      "is_active": true,
      "is_referenced": false,
      "address": "0x00000001017c90e0"
    },
    {
      "type": "loop",
      "is_active": false,
      "address": "0x00000001017dc400"
    }
  ],
  "workers": [],
  "environmentVariables": {
    "TERM_SESSION_ID": "[REDACTED]",
    "SSH_AUTH_SOCK": "[REDACTED]",
    "Apple_PubSub_Socket_Render": "[REDACTED]",
    "COLORFGBG": "15;0",
    "ITERM_PROFILE": "yoyodyne",
    "XPC_FLAGS": "0x0",
    "LANG": "en_US.UTF-8",
    "PWD": "/Users/boneskull/projects/christopher-hiller/report-toolkit",
    "SHELL": "/usr/local/bin/zsh",
    "SECURITYSESSIONID": "[REDACTED]",
    "TERM_PROGRAM_VERSION": "3.2.7beta4",
    "TERM_PROGRAM": "iTerm.app",
    "PATH": "/Users/boneskull/.nvm/versions/node/v12.1.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/ccache/libexec:/opt/X11/bin:./node_modules/.bin:/Users/boneskull/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/boneskull/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/boneskull/.antigen/bundles/zsh-users/zsh-history-substring-search:/Users/boneskull/.antigen/bundles/zsh-users/zsh-completions:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/boneskull/.antigen/bundles/smallhadroncollider/antigen-git-rebase:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-extras:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitignore:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/github:/Users/boneskull/.antigen/bundles/denolfe/zsh-travis:/Users/boneskull/.antigen/bundles/mollifier/cd-gitroot:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/node:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/nvm:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/npm:/Users/boneskull/.antigen/bundles/tomsquest/nvm-auto-use.zsh:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/vagrant:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/bundler:/Users/boneskull/.antigen/bundles/Tarrasch/zsh-mcd:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/osx:/Users/boneskull/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/brew",
    "DISPLAY": "[REDACTED]",
    "COLORTERM": "truecolor",
    "TERM": "xterm-256color",
    "HOME": "/Users/boneskull",
    "USER": "boneskull",
    "XPC_SERVICE_NAME": "0",
    "LOGNAME": "boneskull",
    "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0",
    "ITERM_SESSION_ID": "[REDACTED]",
    "SHLVL": "1",
    "OLDPWD": "/Users/boneskull/projects/christopher-hiller/report-toolkit/test",
    "LESSOPEN": "| /usr/bin/env src-hilite-lesspipe.sh %s 2>/dev/null",
    "LESS": " -R",
